import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import io from "socket.io-client";
import { useEffect , useState , ChangeEvent } from 'react';
let socket:any;

const Home: NextPage = () => {

  const [value , setValue] = useState("");
 
  const [messages,setMessages] = useState<string[]>([]);
 
  async function connectSocket() {

    await fetch("/api/socket");

  }

  function handleClick(){
    socket.emit("message" , value);
    setMessages((prev)=>[...prev, value]);
    
  }
  

  
  useEffect(() => {
      
    connectSocket();
    socket = io();

    socket.on('connect', () => {
      console.log(socket)
    })

    socket.on('receive', (msg:string) => {
      console.log(msg)
      setMessages((prev)=>[...prev, msg]);
      console.log(messages)
    })

  
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>connected users ids..</p>
      
      <input value={value} type='text' onChange={({target}:ChangeEvent<HTMLInputElement>)=>setValue(target.value)}/>
      <button onClick={handleClick}>send</button>
      <p>{messages}</p>
    </div>
  )
}

export default Home
