import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import io from "socket.io-client";
import { useEffect , useState } from 'react';

const Home: NextPage = () => {

  async function connectSocket() {

    await fetch("/api/socket");

  }

  const [ids , setIds] = useState<string[]>([]);

  useEffect(() => {
      
      connectSocket();


      const socket = io();


      socket.on("connect", () => {
          setIds([...ids , socket.id]);
      })
  
  }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>connected users ids..</p>
      <p className='box'>{ids.map((item)=>item)}</p>
    </div>
  )
}

export default Home
